from calculatorpy import Calculator
import sys

obj = Calculator()
print(obj.add(a=2, b=3))
print(obj.add(a=2, b=3))
print(obj.add(a=2, b=3))
print(obj.add(a=2, b=3))
print(obj.divide(a=4, b=6))
print(obj.multiply(a=4, b=6))
print(obj.subtract(a=4, b=6))
print(obj.add(a=4, b=6))
print(obj.add(a=999, b=44))
print(obj.subtract(a=999, b=44))
print(obj.multiply(a=999, b=44))
print(obj.divide(a=999, b=44))
print(obj.add(a=77, b=89))
print(obj.multiply(a=55, b=66))
print(obj.multiply(a=3, b=4))
print(obj.subtract(a=77, b=8999))
print(obj.divide(a=3, b=9))
print(obj.divide(a=3, b=9))
print(obj.add(a=4, b=6))
print(obj.subtract(a=4, b=5))
print(obj.divide(a=3, b=9))
print(obj.divide(a=3, b=9))
print(obj.add(a=4, b=6))
print(obj.add(a=4, b=6))
print(obj.subtract(a=4, b=5))
print(obj.divide(a=3, b=9))
print(obj.add(a=4, b=6))
print(obj.add(a=9, b=8))
