from playlistpy import MusicPlaylist
import sys

obj = MusicPlaylist()
# session runner - commands will be appended below
print(obj.pause())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.skip())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.play())
print(obj.add(a=2, b=3))
print(obj.add(a=2, b=3))
print(obj.subtract(a=5, b=2))
print(obj.__init__())
print(obj.__init__())
