from smarthomepy import SmartHome
import sys

obj = SmartHome()
print(obj.turn_light_off())
print(obj.turn_light_off())
print(obj.turn_ac_on())
print(obj.decrease_temperature())
print(obj.turn_tv_on())
print(obj.turn_light_off())
print(obj.turn_ac_on())
print(obj.decrease_temperature())
print(obj.turn_light_off())
print(obj.turn_ac_on())
print(obj.decrease_temperature())
print(obj.turn_light_off())
print(obj.turn_ac_on())
print(obj.decrease_temperature())
print(obj.turn_light_on())
print(obj.turn_ac_on())
print(obj.turn_light_off())
print(obj.turn_ac_on())
print(obj.decrease_temperature())
print(obj.turn_tv_on())
