from smarthomepy import SmartHome
import sys

obj = SmartHome()
# session runner - commands will be appended below
print(obj.turn_tv_on())
print(obj.turn_tv_off())
print(obj.turn_ac_on())
print(obj.turn_light_on())
print(obj.turn_light_on())
print(obj.increase_temperature())
print(obj.turn_ac_on())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.turn_ac_off())
print(obj.increase_temperature())
print(obj.turn_ac_off())
print(obj.increase_temperature())
print(obj.turn_ac_off())
print(obj.are_all_devices_off())
print(obj.turn_ac_off())
print(obj.turn_ac_on())
print(obj.turn_ac_on())
print(obj.turn_tv_on())
print(obj.turn_tv_on())
print(obj.turn_tv_on())
print(obj.status())
print(obj.status())
print(obj.status())
print(obj.turn_all_on())
print(obj.turn_tv_on())
print(obj.turn_tv_off())
print(obj.turn_tv_on())
print(obj.turn_ac_on())
print(obj.status())
print(obj.status())
